name: Analysis Pipeline (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to run analysis"
        required: true
        default: "NO"

jobs:
  analyse:
    if: github.event.inputs.confirm == 'YES'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (LOCK-FILE SAFE)
        run: npm install --no-audit --no-fund

      - name: Run analysis
        run: npm run analysis:run
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CORE_DB: ${{ secrets.CORE_DB }}
          BRAIN_DB: ${{ secrets.BRAIN_DB }}
          PROJECTS_DB: ${{ secrets.PROJECTS_DB }}
